### ISSUE TITLE
Error with python symlink

### ISSUE THREAD

**Issue by samuelv8** [siphomateke/deezer#24]
I've got the following error when trying to run the install script on Ubuntu 20.04:

```
...
build/main.js 523ms
build/preload.js 90ms
build/renderer.js 58ms
build/service-worker.js 2ms
build/titlebar.js 34ms
patching file build/main.js
Hunk #1 succeeded at 505 (offset 2 lines).
Hunk #2 succeeded at 3081 (offset 2 lines).
patching file build/main.js
Hunk #1 succeeded at 3124 (offset 2 lines).
/usr/lib/node_modules/asar/lib/filesystem.js:101
      throw new Error(`${p}: file "${link}" links out of the package`)
            ^

Error: app/node_modules/abstract-socket/build/node_gyp_bins/python3: file "../../../../../usr/bin/python3.8" links out of the package
    at Filesystem.insertLink (/usr/lib/node_modules/asar/lib/filesystem.js:101:13)
    at handleFile (/usr/lib/node_modules/asar/lib/asar.js:132:20)
    at next (/usr/lib/node_modules/asar/lib/asar.js:148:11)
    at next (/usr/lib/node_modules/asar/lib/asar.js:149:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Successfully installed Deezer Desktop!
```
Looks like a error in node-gyp package (I have Python 2 and 3 versions installed). However, I remember installing correctly this same deezer app in the past (also on Ubuntu 20.04). Any ideas?

**Comment by ghost** [comment]
You could try my fork.

**Comment by samuelv8** [comment]
@mrkenhoo got some error due nodejs related packages. And, yes, I have the nodejs, yarn, gcc etc packages installed.

```
## Run `sudo apt-get install -y nodejs` to install Node.js 14.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
     echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn


Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version (4:9.3.0-1ubuntu2).
make is already the newest version (4.2.1-1.2).
patch is already the newest version (2.7.6-6).
p7zip-full is already the newest version (16.02+dfsg-7build1).
wget is already the newest version (1.20.3-1ubuntu2).
imagemagick is already the newest version (8:6.9.10.23+dfsg-2.1ubuntu11.4).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: nodejs (>= 6.11~)
       Depends: node-abbrev (>= 1.1.1~) but it is not going to be installed
       Depends: node-ajv but it is not going to be installed
...
```

**Comment by ghost** [comment]
Which version of Ubuntu are you using?

**Comment by samuelv8** [comment]
Ubuntu 20.04.5 LTS

**Comment by ghost** [comment]
What about the repositories you have set?

**Comment by samuelv8** [comment]
`nodejs`: 14.21.2-deb-1nodesource1 (which, btw, seems to be broken, so I use version 16 installed via nvm as default).
`gcc`: 9.4.0-1ubuntu1~20.04.1
`make`: GNU Make 4.2.1 Built for x86_64-pc-linux-gnu
`yarn`: 1.22.19

**Comment by ghost** [comment]
Those are not APT repositories.

**Comment by ToMattBan** [comment]
Man. I had this same issue when trying to install it again on my machine and after some searching, I found this thread: https://github.com/nodejs/node-gyp/issues/2713

In the end, what make it work for me is:

Open the install.sh and between line 59 and 60, write
rm -rf app/node_modules/abstract-socket/build/node_gyp_bins/python3

Then run it again.

**Comment by ghost** [comment]
That is already implemented on my fork, in the `add-rpm-packages-support` branch.

**Comment by ToMattBan** [comment]
Yeah, I saw your PR here and your fork after I come with a solution, but for these that don't want to get your fork or something, I put the solution here XD

**Comment by samuelv8** [comment]
@ToMattBan I still got the same error here. Appreciate your help, guys, but I'm actually giving up on Deezer now.

**Comment by ToMattBan** [comment]
@samuelv8 if you are willing to a last try, run every command by hand and when get this error, remove the file mannualy and see if the error persist.

**Comment by alex-arugon** [comment]
> @ToMattBan I still got the same error here. Appreciate your help, guys, but I'm actually giving up on Deezer now.

sad(
